# apiVersion: kappctrl.k14s.io/v1alpha1
# kind: App
# metadata:
#   name: simple-app
#   namespace: default
# spec:
#   serviceAccountName: default-ns-sa
#   fetch:
#     - image:
#         subPath: monitoring
#         url: arttii/dummydeploy
#   template:
#   - command: 
#       cmd: "sops"
#       args: 
#       - '--pgp'
#       - '0F2D7BFF3ACF1384D554037CC27F860A17CBB93B'
#       - '-d'
#       - --input-type=yaml
#       - --output-type=yaml
#       - '/dev/stdin'
    
#       mergeFiles: false
#       match: "*.yaml"
#   deploy:
#   - kapp: {}
 
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app2
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
    - image:
        subPath: monitoring
        url: arttii/dummydeploy:notencrypted
  template:
  - command: 
      cmd: "sed"
      args: 
      - 's/dummy/smart/g'
    
      mergeFiles: true
      match: "*.yaml"
  deploy:
  - kapp: {}