apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
    - image:
        subPath: monitoring
        url: arttii/dummydeploy
  template:
  - sops: 
      pgp:
        - '0F2D7BFF3ACF1384D554037CC27F860A17CBB93B'
  deploy:
  - kapp: {}
